### PR TITLE
switch to Poetry

### PR DESCRIPTION
**Pull request by aerickson**
Move dependency and setup to Poetry (from setup.py and requirements.txt).

### CODE REVIEW

**Comment by petemoore** [comment]
@aerickson Many thanks for the PR! Is this still meant to be in draft, or is it ready for review now?

**Comment by aerickson** [comment]
> @aerickson Many thanks for the PR! Is this still meant to be in draft, or is it ready for review now?

I'd still like to change the .taskcluster.yml file to use Poetry. I will try to work on it soon.

**Comment by aerickson** [comment]
@petemoore How can we get the tests to be red when they fail? 67a459e and 01016d5 should both be failures.

**Comment by aerickson** [comment]
> @petemoore How can we get the tests to be red when they fail? [67a459e](https://github.com/taskcluster/monopacker/commit/67a459e100d7c7b33892e3ffaa4fbd266195569e) and [01016d5](https://github.com/taskcluster/monopacker/commit/01016d53894d1e8216f02d5221c1e53e38685b39) should both be failures.

Figured it out. The script wasn't running with `-e`. Fixed.

**Review by petemoore — APPROVED** [review]
Looks great, thanks @aerickson!

**Pull request merged**
